from pages.base import BasePage
from common.project_path import screen_path


class VoicePages(BasePage):
    img_7 = {"imgName": screen_path + "/7.png"}  # 语音球
    group_mark = {"idname": "com.sabac.hy:id/image_float_item_chat_history_bubble_sub_icon"}  # 群标志
    img_6 = {"imgName": screen_path + "/6.png"}  # 语音球上群标志
    more_menu = {"idname": "com.sabac.hy:id/cb_more_menu"}  # 语音球右上角三个点按钮
    room_btn = {"classname": "android.widget.TextView", "textname": "房间"}  # 语音球中房间按钮
    playmate_btn = {"classname": "android.widget.TextView", "textname": "玩伴"}  # 语音球中玩伴按钮
    msg_btn = {"classname": "android.widget.TextView", "textname": "信息"}  # 语音球中信息按钮
    clear_chat = {"classname": "android.widget.TextView", "textname": "清除聊天记录"}  # 语音球中清除聊天记录按钮
    open_in_hy = {"classname": "android.widget.TextView", "textname": "在欢游中打开"}  # 语音球中在欢游中打开按钮
    voice_btn = {"checkId": "com.sabac.hy:id/chatting_voice_btn"}  # 语音按钮
    input_txt = {"idname": "com.sabac.hy:id/float_im_et_input"}  # 语音球中输入框
    str_msg = '趣玩a123'  # 发送的文本信息
    sent_btn = {"idname": "com.sabac.hy:id/float_im_chatting_sent_btn"}  # 语音球中发送按钮
    msg_context = {"checkId": "com.sabac.hy:id/float_chat_text_msg_content", "checkText": "{}".format(str_msg)}  # 发送的信息是否正常显示
    msg_context2 = {"idname": "com.sabac.hy:id/float_chat_text_msg_content", "textname": "{}".format(str_msg)}
    read_status = {"checkId": "com.sabac.hy:id/tv_message_read_status"}  # 送达标志
    photo_btn = {"idname": "com.sabac.hy:id/float_im_chatting_photo_btn"}  # 图片按钮
    face_btn = {"idname": "com.sabac.hy:id/float_im_chatting_face_btn"}  # 表情按钮
    select_face = {"idname": "com.sabac.hy:id/emoticon_view"}  # 选择的表情
    msg_content = {"checkId": "com.sabac.hy:id/float_chat_text_msg_content", "checkText": "[t000/微笑]"}  # 发送的表情
    select_photo = {"idname": "com.sabac.hy:id/image_item"}  # 选择的图片
    send_image = {"idname": "com.sabac.hy:id/btn_send_image"}  # 点击图片后出现的发送按钮
    content_container = {"checkId": "com.sabac.hy:id/float_chat_content_container"}  # 发送后的图片
    sent_pic = {"idname": "com.sabac.hy:id/float_chat_content_container"}  # 发送后的图片
    big_pic = {"img": screen_path + "/8.png"}  # 放大后的缩略图
    img_10 = {"imgName": screen_path + "/10.png"}  # 收藏图标
    img_01 = {"imgName": screen_path + "/01.png"}  # 热门图标
    img_9 = {"img": screen_path + "/9.png"}  # 发送后的收藏表情
    sticker_image = {"idname": "com.sabac.hy:id/sticker_item_image"}  # 选择的收藏表情
    room_title = {"idname": "com.sabac.hy:id/v_channel_room_title"}  # 要进入的房间名
    entertainment_btn = {"idname": "com.sabac.hy:id/channel_toggle_mode_button", "textname": "娱乐"}  # 房间娱乐按钮
    entertainment_btn_1 = {"checkId": "com.sabac.hy:id/channel_toggle_mode_button", "checkText": "娱乐"}  # 房间娱乐按钮
    black_btn = {"idname": "com.sabac.hy:id/channel_toggle_mode_button", "textname": "开黑"}  # 房间开黑按钮
    black_btn_1 = {"checkId": "com.sabac.hy:id/channel_toggle_mode_button", "checkText": "开黑"}  # 房间开黑按钮
    entertain_room = {"classname": "android.widget.TextView", "textname": "娱乐房"}  # 娱乐房间
    black_room = {"classname": "android.widget.TextView", "textname": "高音质开黑房"}  # 高音质开黑房房间
    quit_button = {"idname": "com.sabac.hy:id/channel_quit_button"}  # 房间内右上角退出按钮
    confirm_button = {"idname": "com.sabac.hy:id/float_chat_dialog_confirm_button"}  # 确定按钮
    music_icon = {"checkId": "com.sabac.hy:id/music_icon"}  # 我的房间音乐图标
    empty_wheat = {"idname": "com.sabac.hy:id/channel_admin_avatar"}   # 空麦位
    empty = {"idname": "com.sabac.hy:id/normal_channel_chairman_mic"}  # 空麦位
    upper_wheat = {"idname": "com.sabac.hy:id/tv_dialog_select_text", "textname": "上麦"}  # 上麦按钮
    img_04 = {"imgName": screen_path + "/04.png"}  # 空麦位
    close_wheat = {"idname": "com.sabac.hy:id/tv_dialog_select_text", "textname": "设为闭麦位"}  # 闭麦位按钮
    success = {"checkId": "com.sabac.hy:id/chairman_mic_desc_view"}  # 上麦成功
    success_wheat = {"checkId": "com.sabac.hy:id/channel_mic_user_desc_icon"}  # 上麦成功或闭麦的标志
    more_btn = {"idname": "com.sabac.hy:id/chatting_more_btn"}  # 语音房间里面更多按钮
    invite_friend = {"idname": "com.sabac.hy:id/float_chat_more_content",  "textname": "邀请玩伴"}  # 邀请玩伴按钮
    public_members = {"classname": "android.widget.TextView", "textname": "选择公会成员"}  # 选择公会成员按钮
    float_name = {"idname": "com.sabac.hy:id/firend_float_name"}  # 联系人名字
    confirm_btn = {"idname": "com.sabac.hy:id/confirm_button"}  # 点击联系人后出现的发送按钮
    img_02 = {"img": screen_path + "/02.png"}  # 发送邀请成功后弹出的提示语
    silence_btn = {"idname": "com.sabac.hy:id/float_chat_more_content",  "textname": "静音"}  # 静音按钮
    silence_in = {"checkId": "com.sabac.hy:id/float_chat_more_content", "checkText": "静音中"}  # 静音中按钮
    img_03 = {"imgName": screen_path + "/03.png"}  # 我的房间图标
    hot_btn = {"classname": "android.widget.TextView", "textname": "热门"}  # 点击房间后弹出的热门按钮
    hot_title = {"idname": "com.sabac.hy:id/flow_hot_channel_title"}  # 热门中任意的一个房间
    hot_channel_title = {"checkId": "com.sabac.hy:id/flow_hot_channel_title"}  # 热门中任意的一个房间
    btn_confirm = {"idname": "com.sabac.hy:id/btn_confirm"}  # 点击热门房间后弹出的确定按钮
    collect_button = {"checkId": "com.sabac.hy:id/channel_collect_button", "checkText": "收藏"}  # 热门房间中的收藏按钮
    public_btn = {"classname": "android.widget.TextView", "textname": "公会房间"}  # 点击房间后弹出的公会房间按钮
    public_test = {"idname": "com.sabac.hy:id/flow_channel_guild_room_title", "textname": "公会测试"}  # 公会测试娱乐房
    guild_room_title = {"checkId": "com.sabac.hy:id/flow_channel_guild_room_title"}  # 任意的公会房间名
    public_test_display = {"checkId": "com.sabac.hy:id/channel_name_text_view", "checkText": "公会测试"}  # 进入房间后显示的公会名字
    guild_house = {"idname": "com.sabac.hy:id/flow_channel_guild_room_title", "textname": "hh"}  # 公会内部房名字
    invite_more = {"idname": "com.sabac.hy:id/float_chat_more_content", "textname": "一键召集"}  # 一键召集按钮
    dialog_confirm = {"idname": "com.sabac.hy:id/dialog_confirm"}  # 点击一键召集后弹出的确定按钮
    invite_num = {"checkId": "com.sabac.hy:id/tv_invite_user_num"}  # 召集成功的标志
    invite = {"idname": "com.sabac.hy:id/tv_invite_user_num"}  # 已经召集
    cancel_invite = {"idname": "com.sabac.hy:id/float_convene_member_list_cancel"}  # 取消召集按钮
    friend_name = {"idname": "com.sabac.hy:id/v_channel_friend_name"}  # 任意的开黑房间
    room_number = {"idname": "com.sabac.hy:id/v_channel_room_title", "textname": "找个师父"}  # 要进入的收藏房间名
    search_view = {"idname": "com.sabac.hy:id/v_search_view"}  # 语音球中点击房间按钮后出现的搜索框
    v_search = {"idname": "com.sabac.hy:id/v_search"}  # 搜索按钮
    channel_count = {"checkId": "com.sabac.hy:id/v_channel_count"}  # 输入房间号搜索出来的房间信息
    hall_btn = {"classname": "android.widget.TextView", "textname": "大厅"}  # 大厅按钮
    guild_room_title = {"checkId": "com.sabac.hy:id/flow_channel_guild_room_title"}  # 大厅里面的房间名
